baseURL = "https://www.pipehow.tech/"
languageCode = "en-us"
title = "| How"
theme = "hyde"
disqusShortname = "emanuelpalm"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true

[params]
titleHeader = "PowerShell and Technology Blogging"
titleText = "PipeHow"
introduction = "PowerShell, C#, .NET - and other tidbits of fun."
description = "Website and blog of Swedish IT viking Emanuel Palm about his quest for knowledge - and the silly adventures along the way."
keywords = "C#, PowerShell, .NET, DotNet, Blog, Automation, Technology, Development"
location = "Stockholm, Sweden"
author = "Emanuel Palm"
githubURL = "https://github.com/MrEpiX"
linkedinURL = "https://www.linkedin.com/in/palmemanuel/"

[blackfriday]
hrefTargetBlank = true
